import type { CompetitiveProblem } from "./problem-schemas";

export const problemSeeds: CompetitiveProblem[] = [

  // ═══════════════════════════════════════
  // EASY (35 problems)
  // ═══════════════════════════════════════

  {
    mode: "competitive", title: "Two Sum",
    statement: "Given an array of integers and a target, return the two numbers that add up to the target in ascending order. Exactly one solution exists.",
    difficulty: "easy",
    constraints: ["2 <= nums.length <= 1000", "-1000 <= nums[i] <= 1000"],
    functionSignature: { name: "twoSum", params: [{ name: "nums", type: "number[]" }, { name: "target", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[2,7,11,15], 9], output: [2,7], explanation: "2+7=9" }],
    testCases: [
      { args: [[2,7,11,15], 9], expectedOutput: [2,7], isHidden: false },
      { args: [[3,2,4], 6], expectedOutput: [2,4], isHidden: false },
      { args: [[3,3], 6], expectedOutput: [3,3], isHidden: true },
      { args: [[1,5,3,7], 8], expectedOutput: [1,7], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Reverse Array",
    statement: "Given an array of integers, return a new array with elements in reversed order.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000"],
    functionSignature: { name: "reverseArray", params: [{ name: "arr", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4,5]], output: [5,4,3,2,1] }],
    testCases: [
      { args: [[1,2,3,4,5]], expectedOutput: [5,4,3,2,1], isHidden: false },
      { args: [[1,2]], expectedOutput: [2,1], isHidden: false },
      { args: [[5]], expectedOutput: [5], isHidden: true },
      { args: [[1,2,3]], expectedOutput: [3,2,1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Element",
    statement: "Given an array of integers, return the largest element.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-10000 <= arr[i] <= 10000"],
    functionSignature: { name: "maxElement", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[3,1,4,1,5,9,2,6]], output: 9 }],
    testCases: [
      { args: [[3,1,4,1,5,9,2,6]], expectedOutput: 9, isHidden: false },
      { args: [[-1,-5,-2,-3]], expectedOutput: -1, isHidden: false },
      { args: [[7]], expectedOutput: 7, isHidden: true },
      { args: [[1,2,3,4,5]], expectedOutput: 5, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Single Number",
    statement: "Every element appears twice except one. Return the element that appears only once.",
    difficulty: "easy",
    constraints: ["1 <= nums.length <= 1000", "All elements except one appear exactly twice"],
    functionSignature: { name: "singleNumber", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[4,1,2,1,2]], output: 4 }],
    testCases: [
      { args: [[2,2,1]], expectedOutput: 1, isHidden: false },
      { args: [[4,1,2,1,2]], expectedOutput: 4, isHidden: false },
      { args: [[1]], expectedOutput: 1, isHidden: true },
      { args: [[5,3,3]], expectedOutput: 5, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Fibonacci Number",
    statement: "Return the nth Fibonacci number. Sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55...",
    difficulty: "easy",
    constraints: ["0 <= n <= 30"],
    functionSignature: { name: "fibonacci", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [5], output: 5, explanation: "0,1,1,2,3,5 — index 5 is 5" }],
    testCases: [
      { args: [0], expectedOutput: 0, isHidden: false },
      { args: [1], expectedOutput: 1, isHidden: false },
      { args: [5], expectedOutput: 5, isHidden: true },
      { args: [10], expectedOutput: 55, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count Occurrences",
    statement: "Given an array and a target value, return how many times the target appears in the array.",
    difficulty: "easy",
    constraints: ["0 <= arr.length <= 1000", "-1000 <= arr[i], target <= 1000"],
    functionSignature: { name: "countOccurrences", params: [{ name: "arr", type: "number[]" }, { name: "target", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,2,2,3,3,3], 3], output: 3 }],
    testCases: [
      { args: [[1,2,2,3,3,3], 3], expectedOutput: 3, isHidden: false },
      { args: [[1,2,3], 4], expectedOutput: 0, isHidden: false },
      { args: [[5,5,5,5], 5], expectedOutput: 4, isHidden: true },
      { args: [[1], 1], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Sum of Digits",
    statement: "Given a non-negative integer, return the sum of its digits.",
    difficulty: "easy",
    constraints: ["0 <= n <= 10^9"],
    functionSignature: { name: "sumOfDigits", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [1234], output: 10, explanation: "1+2+3+4=10" }],
    testCases: [
      { args: [1234], expectedOutput: 10, isHidden: false },
      { args: [0], expectedOutput: 0, isHidden: false },
      { args: [999], expectedOutput: 27, isHidden: true },
      { args: [100], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Is Palindrome Number",
    statement: "Given an integer, return true if it reads the same forwards and backwards, false otherwise. Negative numbers are never palindromes.",
    difficulty: "easy",
    constraints: ["-2^31 <= n <= 2^31 - 1"],
    functionSignature: { name: "isPalindromeNumber", params: [{ name: "n", type: "number" }], returnType: "boolean" },
    examples: [{ args: [121], output: true }, { args: [-121], output: false }],
    testCases: [
      { args: [121], expectedOutput: true, isHidden: false },
      { args: [-121], expectedOutput: false, isHidden: false },
      { args: [10], expectedOutput: false, isHidden: true },
      { args: [1221], expectedOutput: true, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Power of Two",
    statement: "Given an integer n, return true if n is a power of two, otherwise return false.",
    difficulty: "easy",
    constraints: ["-2^31 <= n <= 2^31 - 1"],
    functionSignature: { name: "isPowerOfTwo", params: [{ name: "n", type: "number" }], returnType: "boolean" },
    examples: [{ args: [16], output: true }, { args: [3], output: false }],
    testCases: [
      { args: [1], expectedOutput: true, isHidden: false },
      { args: [16], expectedOutput: true, isHidden: false },
      { args: [3], expectedOutput: false, isHidden: true },
      { args: [0], expectedOutput: false, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "FizzBuzz Single",
    statement: "Given a number n, return 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, 'FizzBuzz' if divisible by both, otherwise return the number as a string.",
    difficulty: "easy",
    constraints: ["1 <= n <= 10000"],
    functionSignature: { name: "fizzBuzz", params: [{ name: "n", type: "number" }], returnType: "string" },
    examples: [{ args: [15], output: "FizzBuzz" }, { args: [7], output: "7" }],
    testCases: [
      { args: [3], expectedOutput: "Fizz", isHidden: false },
      { args: [5], expectedOutput: "Buzz", isHidden: false },
      { args: [15], expectedOutput: "FizzBuzz", isHidden: true },
      { args: [7], expectedOutput: "7", isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Remove Duplicates",
    statement: "Given a sorted array, return a new array with all duplicates removed, maintaining order.",
    difficulty: "easy",
    constraints: ["0 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000", "Array is sorted in ascending order"],
    functionSignature: { name: "removeDuplicates", params: [{ name: "arr", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,1,2,3,3,4]], output: [1,2,3,4] }],
    testCases: [
      { args: [[1,1,2,3,3,4]], expectedOutput: [1,2,3,4], isHidden: false },
      { args: [[1,2,3]], expectedOutput: [1,2,3], isHidden: false },
      { args: [[1,1,1]], expectedOutput: [1], isHidden: true },
      { args: [[-2,-1,-1,0]], expectedOutput: [-2,-1,0], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count Vowels",
    statement: "Given a string, return the number of vowels (a, e, i, o, u) it contains. Case-insensitive.",
    difficulty: "easy",
    constraints: ["0 <= s.length <= 1000", "s contains only English letters"],
    functionSignature: { name: "countVowels", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["Hello World"], output: 3, explanation: "e, o, o" }],
    testCases: [
      { args: ["Hello World"], expectedOutput: 3, isHidden: false },
      { args: ["aeiou"], expectedOutput: 5, isHidden: false },
      { args: ["rhythm"], expectedOutput: 0, isHidden: true },
      { args: ["AEIOU"], expectedOutput: 5, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Is Anagram",
    statement: "Given two strings, return true if they are anagrams of each other (same characters, same frequencies), false otherwise. Case-sensitive.",
    difficulty: "easy",
    constraints: ["1 <= s.length, t.length <= 1000", "Strings contain only lowercase letters"],
    functionSignature: { name: "isAnagram", params: [{ name: "s", type: "string" }, { name: "t", type: "string" }], returnType: "boolean" },
    examples: [{ args: ["anagram", "nagaram"], output: true }],
    testCases: [
      { args: ["anagram", "nagaram"], expectedOutput: true, isHidden: false },
      { args: ["rat", "car"], expectedOutput: false, isHidden: false },
      { args: ["a", "a"], expectedOutput: true, isHidden: true },
      { args: ["ab", "ba"], expectedOutput: true, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "GCD of Two Numbers",
    statement: "Given two positive integers, return their greatest common divisor (GCD).",
    difficulty: "easy",
    constraints: ["1 <= a, b <= 10^6"],
    functionSignature: { name: "gcd", params: [{ name: "a", type: "number" }, { name: "b", type: "number" }], returnType: "number" },
    examples: [{ args: [48, 18], output: 6 }],
    testCases: [
      { args: [48, 18], expectedOutput: 6, isHidden: false },
      { args: [7, 3], expectedOutput: 1, isHidden: false },
      { args: [100, 75], expectedOutput: 25, isHidden: true },
      { args: [12, 12], expectedOutput: 12, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Sum of Array",
    statement: "Given an array of integers, return the sum of all its elements.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000"],
    functionSignature: { name: "sumArray", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,4,5]], output: 15 }],
    testCases: [
      { args: [[1,2,3,4,5]], expectedOutput: 15, isHidden: false },
      { args: [[-1,0,1]], expectedOutput: 0, isHidden: false },
      { args: [[7]], expectedOutput: 7, isHidden: true },
      { args: [[-5,-4,-3]], expectedOutput: -12, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Intersection of Two Arrays",
    statement: "Given two arrays, return a sorted array of their unique common elements.",
    difficulty: "easy",
    constraints: ["0 <= arr1.length, arr2.length <= 1000", "-1000 <= arr1[i], arr2[i] <= 1000"],
    functionSignature: { name: "intersection", params: [{ name: "arr1", type: "number[]" }, { name: "arr2", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,2,2,1],[2,2]], output: [2] }],
    testCases: [
      { args: [[1,2,2,1],[2,2]], expectedOutput: [2], isHidden: false },
      { args: [[4,9,5],[9,4,9,8,4]], expectedOutput: [4,9], isHidden: false },
      { args: [[1,2],[3,4]], expectedOutput: [], isHidden: true },
      { args: [[1,2,3],[1,2,3]], expectedOutput: [1,2,3], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count Even Numbers",
    statement: "Given an array of integers, return the count of even numbers.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-10000 <= arr[i] <= 10000"],
    functionSignature: { name: "countEvens", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,4,5,6]], output: 3 }],
    testCases: [
      { args: [[1,2,3,4,5,6]], expectedOutput: 3, isHidden: false },
      { args: [[1,3,5]], expectedOutput: 0, isHidden: false },
      { args: [[2,4,6,8]], expectedOutput: 4, isHidden: true },
      { args: [[0]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Reverse String",
    statement: "Given a string, return its reverse.",
    difficulty: "easy",
    constraints: ["0 <= s.length <= 1000"],
    functionSignature: { name: "reverseString", params: [{ name: "s", type: "string" }], returnType: "string" },
    examples: [{ args: ["hello"], output: "olleh" }],
    testCases: [
      { args: ["hello"], expectedOutput: "olleh", isHidden: false },
      { args: ["abcd"], expectedOutput: "dcba", isHidden: false },
      { args: ["a"], expectedOutput: "a", isHidden: true },
      { args: ["racecar"], expectedOutput: "racecar", isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Second Largest",
    statement: "Given an array of distinct integers with at least 2 elements, return the second largest element.",
    difficulty: "easy",
    constraints: ["2 <= arr.length <= 1000", "-10000 <= arr[i] <= 10000", "All elements are distinct"],
    functionSignature: { name: "secondLargest", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[12,35,1,10,34,1]], output: 34, explanation: "Largest is 35, second is 34" }],
    testCases: [
      { args: [[12,35,1,10,34]], expectedOutput: 34, isHidden: false },
      { args: [[1,2]], expectedOutput: 1, isHidden: false },
      { args: [[5,3,1,4,2]], expectedOutput: 4, isHidden: true },
      { args: [[-1,-2,-3]], expectedOutput: -2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count Primes Below N",
    statement: "Given a non-negative integer n, return the number of prime numbers strictly less than n.",
    difficulty: "easy",
    constraints: ["0 <= n <= 5000"],
    functionSignature: { name: "countPrimes", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [10], output: 4, explanation: "Primes: 2, 3, 5, 7" }],
    testCases: [
      { args: [10], expectedOutput: 4, isHidden: false },
      { args: [0], expectedOutput: 0, isHidden: false },
      { args: [1], expectedOutput: 0, isHidden: true },
      { args: [20], expectedOutput: 8, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Array Product Except Self (Brute Force)",
    statement: "Given an array of integers, return an array where each element at index i is the product of all elements except the one at index i. Do not divide.",
    difficulty: "easy",
    constraints: ["2 <= nums.length <= 10", "-10 <= nums[i] <= 10", "Product of any prefix or suffix fits in 32-bit integer"],
    functionSignature: { name: "productExceptSelf", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4]], output: [24,12,8,6] }],
    testCases: [
      { args: [[1,2,3,4]], expectedOutput: [24,12,8,6], isHidden: false },
      { args: [[-1,1,0,-3,3]], expectedOutput: [0,0,9,0,0], isHidden: false },
      { args: [[2,3]], expectedOutput: [3,2], isHidden: true },
      { args: [[1,2,3]], expectedOutput: [6,3,2], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Factorial",
    statement: "Given a non-negative integer n, return its factorial (n!). 0! = 1.",
    difficulty: "easy",
    constraints: ["0 <= n <= 12"],
    functionSignature: { name: "factorial", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [5], output: 120, explanation: "5*4*3*2*1=120" }],
    testCases: [
      { args: [5], expectedOutput: 120, isHidden: false },
      { args: [0], expectedOutput: 1, isHidden: false },
      { args: [1], expectedOutput: 1, isHidden: true },
      { args: [10], expectedOutput: 3628800, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Is Sorted",
    statement: "Given an array of integers, return true if it is sorted in non-decreasing order, false otherwise.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000"],
    functionSignature: { name: "isSorted", params: [{ name: "arr", type: "number[]" }], returnType: "boolean" },
    examples: [{ args: [[1,2,3,4,5]], output: true }],
    testCases: [
      { args: [[1,2,3,4,5]], expectedOutput: true, isHidden: false },
      { args: [[5,4,3,2,1]], expectedOutput: false, isHidden: false },
      { args: [[1,1,2,3]], expectedOutput: true, isHidden: true },
      { args: [[1,3,2]], expectedOutput: false, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Sum of Odd Numbers",
    statement: "Given an array of integers, return the sum of all odd numbers in the array.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000"],
    functionSignature: { name: "sumOdds", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,4,5]], output: 9, explanation: "1+3+5=9" }],
    testCases: [
      { args: [[1,2,3,4,5]], expectedOutput: 9, isHidden: false },
      { args: [[2,4,6]], expectedOutput: 0, isHidden: false },
      { args: [[-1,-2,-3]], expectedOutput: -4, isHidden: true },
      { args: [[7]], expectedOutput: 7, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Largest Digit",
    statement: "Given a non-negative integer, return its largest digit.",
    difficulty: "easy",
    constraints: ["0 <= n <= 10^9"],
    functionSignature: { name: "largestDigit", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [3947], output: 9 }],
    testCases: [
      { args: [3947], expectedOutput: 9, isHidden: false },
      { args: [1111], expectedOutput: 1, isHidden: false },
      { args: [0], expectedOutput: 0, isHidden: true },
      { args: [9080706], expectedOutput: 9, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Flatten Nested Array One Level",
    statement: "Given an array that may contain nested arrays (one level deep), return a flattened version.",
    difficulty: "easy",
    constraints: ["0 <= arr.length <= 100", "Nested arrays are at most one level deep"],
    functionSignature: { name: "flattenOne", params: [{ name: "arr", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4,5]], output: [1,2,3,4,5] }],
    testCases: [
      { args: [[1,2,3]], expectedOutput: [1,2,3], isHidden: false },
      { args: [[]], expectedOutput: [], isHidden: false },
      { args: [[1,2,3,4,5]], expectedOutput: [1,2,3,4,5], isHidden: true },
      { args: [[7,8,9]], expectedOutput: [7,8,9], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count Negative Numbers",
    statement: "Given an array, return the count of strictly negative numbers.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000"],
    functionSignature: { name: "countNegatives", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[-1,2,-3,4,-5]], output: 3 }],
    testCases: [
      { args: [[-1,2,-3,4,-5]], expectedOutput: 3, isHidden: false },
      { args: [[1,2,3]], expectedOutput: 0, isHidden: false },
      { args: [[-1,-2,-3]], expectedOutput: 3, isHidden: true },
      { args: [[0,-1]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Number to Binary String",
    statement: "Given a positive integer, return its binary representation as a string (without the '0b' prefix).",
    difficulty: "easy",
    constraints: ["1 <= n <= 10000"],
    functionSignature: { name: "toBinary", params: [{ name: "n", type: "number" }], returnType: "string" },
    examples: [{ args: [10], output: "1010" }],
    testCases: [
      { args: [10], expectedOutput: "1010", isHidden: false },
      { args: [1], expectedOutput: "1", isHidden: false },
      { args: [8], expectedOutput: "1000", isHidden: true },
      { args: [255], expectedOutput: "11111111", isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Array Chunk",
    statement: "Given an array and a chunk size k, split the array into groups of size k. The last chunk may be smaller.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 100", "1 <= k <= arr.length"],
    functionSignature: { name: "chunkArray", params: [{ name: "arr", type: "number[]" }, { name: "k", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4,5], 2], output: [1,2,3,4,5], explanation: "Returns flattened result of chunks" }],
    testCases: [
      { args: [[1,2,3,4,5,6], 2], expectedOutput: [1,2,3,4,5,6], isHidden: false },
      { args: [[1,2,3], 1], expectedOutput: [1,2,3], isHidden: false },
      { args: [[1,2,3,4,5], 3], expectedOutput: [1,2,3,4,5], isHidden: true },
      { args: [[1,2], 5], expectedOutput: [1,2], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "String Compression Length",
    statement: "Given a string of repeated characters, return the length of its run-length encoded version. For 'aabcccdddd' return 8 (a2b1c3d4).",
    difficulty: "easy",
    constraints: ["1 <= s.length <= 1000", "s contains only lowercase letters"],
    functionSignature: { name: "compressedLength", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["aabcccdddd"], output: 8, explanation: "a2b1c3d4 has 8 chars" }],
    testCases: [
      { args: ["aabcccdddd"], expectedOutput: 8, isHidden: false },
      { args: ["a"], expectedOutput: 2, isHidden: false },
      { args: ["aaa"], expectedOutput: 2, isHidden: true },
      { args: ["abcd"], expectedOutput: 8, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "First Non-Repeating Character",
    statement: "Given a string of lowercase letters, return the index of the first character that does not repeat. If none exists, return -1.",
    difficulty: "easy",
    constraints: ["1 <= s.length <= 1000", "s contains only lowercase letters"],
    functionSignature: { name: "firstUniqueChar", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["leetcode"], output: 0, explanation: "'l' appears once, at index 0" }],
    testCases: [
      { args: ["leetcode"], expectedOutput: 0, isHidden: false },
      { args: ["aabb"], expectedOutput: -1, isHidden: false },
      { args: ["aab"], expectedOutput: 2, isHidden: true },
      { args: ["z"], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Min Steps to One",
    statement: "Given a positive integer n, return the minimum number of steps to reduce it to 1. Each step you may subtract 1, divide by 2 (if even), or divide by 3 (if divisible).",
    difficulty: "easy",
    constraints: ["1 <= n <= 1000"],
    functionSignature: { name: "minSteps", params: [{ name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [10], output: 3, explanation: "10 -> 9 (/3 isn't exact, 10-1=9) -> 3 (/3) -> 1" }],
    testCases: [
      { args: [1], expectedOutput: 0, isHidden: false },
      { args: [4], expectedOutput: 2, isHidden: false },
      { args: [10], expectedOutput: 3, isHidden: true },
      { args: [6], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Duplicate Count",
    statement: "Given an array, return how many elements appear more than once (count each duplicate element once).",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 1000", "-1000 <= arr[i] <= 1000"],
    functionSignature: { name: "duplicateCount", params: [{ name: "arr", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,2,1]], output: 2, explanation: "1 and 2 are duplicates" }],
    testCases: [
      { args: [[1,2,3,2,1]], expectedOutput: 2, isHidden: false },
      { args: [[1,2,3]], expectedOutput: 0, isHidden: false },
      { args: [[1,1,1,1]], expectedOutput: 1, isHidden: true },
      { args: [[1,2,2,3,3,3]], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Celsius to Fahrenheit Array",
    statement: "Given an array of temperatures in Celsius, return an array of those temperatures converted to Fahrenheit. F = C * 9/5 + 32. Round to nearest integer.",
    difficulty: "easy",
    constraints: ["1 <= arr.length <= 100", "-100 <= arr[i] <= 100"],
    functionSignature: { name: "celsiusToFahrenheit", params: [{ name: "temps", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[0, 100]], output: [32, 212] }],
    testCases: [
      { args: [[0, 100]], expectedOutput: [32, 212], isHidden: false },
      { args: [[-40]], expectedOutput: [-40], isHidden: false },
      { args: [[37]], expectedOutput: [99], isHidden: true },
      { args: [[0]], expectedOutput: [32], isHidden: true },
    ],
    sourceKind: "permissive",
  },

  // ═══════════════════════════════════════
  // MEDIUM (35 problems)
  // ═══════════════════════════════════════

  {
    mode: "competitive", title: "Maximum Subarray Sum",
    statement: "Find the contiguous subarray with the largest sum and return its sum. The array has at least one element.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "maxSubarraySum", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[-2,1,-3,4,-1,2,1,-5,4]], output: 6, explanation: "[4,-1,2,1] sums to 6" }],
    testCases: [
      { args: [[-2,1,-3,4,-1,2,1,-5,4]], expectedOutput: 6, isHidden: false },
      { args: [[1]], expectedOutput: 1, isHidden: false },
      { args: [[-1,-2,-3]], expectedOutput: -1, isHidden: true },
      { args: [[5,4,-1,7,8]], expectedOutput: 23, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Merge Sorted Arrays",
    statement: "Given two sorted arrays, merge them into a single sorted array and return it.",
    difficulty: "medium",
    constraints: ["0 <= arr1.length, arr2.length <= 1000"],
    functionSignature: { name: "mergeSortedArrays", params: [{ name: "arr1", type: "number[]" }, { name: "arr2", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,3,5],[2,4,6]], output: [1,2,3,4,5,6] }],
    testCases: [
      { args: [[1,3,5],[2,4,6]], expectedOutput: [1,2,3,4,5,6], isHidden: false },
      { args: [[1,2,3],[]], expectedOutput: [1,2,3], isHidden: false },
      { args: [[],[1,2]], expectedOutput: [1,2], isHidden: true },
      { args: [[1,1,1],[1,1,1]], expectedOutput: [1,1,1,1,1,1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Missing Number",
    statement: "An array contains n distinct numbers from 0 to n with one missing. Return the missing number.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "0 <= nums[i] <= nums.length"],
    functionSignature: { name: "missingNumber", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[3,0,1]], output: 2 }],
    testCases: [
      { args: [[3,0,1]], expectedOutput: 2, isHidden: false },
      { args: [[0,1]], expectedOutput: 2, isHidden: false },
      { args: [[0]], expectedOutput: 1, isHidden: true },
      { args: [[9,6,4,2,3,5,7,0,1]], expectedOutput: 8, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Longest Common Prefix",
    statement: "Find the longest common prefix string among an array of strings. Return empty string if none exists.",
    difficulty: "medium",
    constraints: ["1 <= strs.length <= 200", "0 <= strs[i].length <= 200"],
    functionSignature: { name: "longestCommonPrefix", params: [{ name: "strs", type: "string[]" }], returnType: "string" },
    examples: [{ args: [["flower","flow","flight"]], output: "fl" }],
    testCases: [
      { args: [["flower","flow","flight"]], expectedOutput: "fl", isHidden: false },
      { args: [["dog","racecar","car"]], expectedOutput: "", isHidden: false },
      { args: [["abc","abc","abc"]], expectedOutput: "abc", isHidden: true },
      { args: [["a"]], expectedOutput: "a", isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Move Zeroes",
    statement: "Move all zeroes in an array to the end while maintaining the relative order of non-zero elements. Return the modified array.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000"],
    functionSignature: { name: "moveZeroes", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[0,1,0,3,12]], output: [1,3,12,0,0] }],
    testCases: [
      { args: [[0,1,0,3,12]], expectedOutput: [1,3,12,0,0], isHidden: false },
      { args: [[0]], expectedOutput: [0], isHidden: false },
      { args: [[1,2,3]], expectedOutput: [1,2,3], isHidden: true },
      { args: [[0,0,1]], expectedOutput: [1,0,0], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Rotate Array",
    statement: "Rotate an array to the right by k steps and return the result.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "0 <= k <= 10000"],
    functionSignature: { name: "rotateArray", params: [{ name: "nums", type: "number[]" }, { name: "k", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4,5,6,7], 3], output: [5,6,7,1,2,3,4] }],
    testCases: [
      { args: [[1,2,3,4,5,6,7], 3], expectedOutput: [5,6,7,1,2,3,4], isHidden: false },
      { args: [[-1,-100,3,99], 2], expectedOutput: [3,99,-1,-100], isHidden: false },
      { args: [[1,2], 3], expectedOutput: [2,1], isHidden: true },
      { args: [[1], 5], expectedOutput: [1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Valid Balanced Parentheses",
    statement: "Given a string of only '(' and ')', return true if every opening bracket has a matching closing bracket in the correct order.",
    difficulty: "medium",
    constraints: ["0 <= s.length <= 1000", "s contains only '(' and ')'"],
    functionSignature: { name: "isBalanced", params: [{ name: "s", type: "string" }], returnType: "boolean" },
    examples: [{ args: ["(())"], output: true }, { args: ["(()"], output: false }],
    testCases: [
      { args: ["(())"], expectedOutput: true, isHidden: false },
      { args: ["(()"], expectedOutput: false, isHidden: false },
      { args: [""], expectedOutput: true, isHidden: true },
      { args: [")("], expectedOutput: false, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Binary Search",
    statement: "Given a sorted array and a target, return the index of the target using binary search. Return -1 if not found.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "-10000 <= nums[i], target <= 10000"],
    functionSignature: { name: "binarySearch", params: [{ name: "nums", type: "number[]" }, { name: "target", type: "number" }], returnType: "number" },
    examples: [{ args: [[-1,0,3,5,9,12], 9], output: 4 }],
    testCases: [
      { args: [[-1,0,3,5,9,12], 9], expectedOutput: 4, isHidden: false },
      { args: [[-1,0,3,5,9,12], 2], expectedOutput: -1, isHidden: false },
      { args: [[1], 1], expectedOutput: 0, isHidden: true },
      { args: [[2,5], 5], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Find Peak Element",
    statement: "A peak element is strictly greater than its neighbors. Given an array, return the index of any peak element. Assume arr[-1] and arr[n] are -infinity.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "-10000 <= nums[i] <= 10000", "nums[i] != nums[i+1] for all valid i"],
    functionSignature: { name: "findPeakElement", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,1]], output: 2, explanation: "Index 2 (value 3) is a peak" }],
    testCases: [
      { args: [[1,2,3,1]], expectedOutput: 2, isHidden: false },
      { args: [[1,2,1,3,5,6,4]], expectedOutput: 5, isHidden: false },
      { args: [[1]], expectedOutput: 0, isHidden: true },
      { args: [[3,2,1]], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Majority Element",
    statement: "Given an array of size n, return the majority element — the element that appears more than n/2 times. It always exists.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "majorityElement", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[3,2,3]], output: 3 }],
    testCases: [
      { args: [[3,2,3]], expectedOutput: 3, isHidden: false },
      { args: [[2,2,1,1,1,2,2]], expectedOutput: 2, isHidden: false },
      { args: [[1]], expectedOutput: 1, isHidden: true },
      { args: [[1,1,2]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Sort Array by Parity",
    statement: "Given an array, return a new array where all even integers come first, followed by all odd integers. Order within each group does not matter.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "0 <= nums[i] <= 10000"],
    functionSignature: { name: "sortByParity", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[3,1,2,4]], output: [2,4,3,1] }],
    testCases: [
      { args: [[3,1,2,4]], expectedOutput: [2,4,3,1], isHidden: false },
      { args: [[2,4,6]], expectedOutput: [2,4,6], isHidden: false },
      { args: [[1,3,5]], expectedOutput: [1,3,5], isHidden: true },
      { args: [[0,1]], expectedOutput: [0,1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Depth of Balanced Parens",
    statement: "Given a valid string of '(' and ')', return the maximum nesting depth.",
    difficulty: "medium",
    constraints: ["1 <= s.length <= 1000", "s is a valid parentheses string"],
    functionSignature: { name: "maxDepth", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["((()))"], output: 3 }],
    testCases: [
      { args: ["((()))"], expectedOutput: 3, isHidden: false },
      { args: ["()()"], expectedOutput: 1, isHidden: false },
      { args: ["()(()())"], expectedOutput: 2, isHidden: true },
      { args: ["(((())))"], expectedOutput: 4, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Subarray Sum Equals K",
    statement: "Given an array and a target k, return the total number of contiguous subarrays whose elements sum to k.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 500", "-100 <= nums[i] <= 100", "-10000 <= k <= 10000"],
    functionSignature: { name: "subarraySum", params: [{ name: "nums", type: "number[]" }, { name: "k", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,1,1], 2], output: 2 }],
    testCases: [
      { args: [[1,1,1], 2], expectedOutput: 2, isHidden: false },
      { args: [[1,2,3], 3], expectedOutput: 2, isHidden: false },
      { args: [[1], 1], expectedOutput: 1, isHidden: true },
      { args: [[-1,-1,1], 0], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Longest Substring Without Repeating",
    statement: "Given a string, return the length of the longest substring without repeating characters.",
    difficulty: "medium",
    constraints: ["0 <= s.length <= 5000", "s consists of English letters, digits, symbols and spaces"],
    functionSignature: { name: "lengthOfLongestSubstring", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["abcabcbb"], output: 3, explanation: "'abc' has length 3" }],
    testCases: [
      { args: ["abcabcbb"], expectedOutput: 3, isHidden: false },
      { args: ["bbbbb"], expectedOutput: 1, isHidden: false },
      { args: ["pwwkew"], expectedOutput: 3, isHidden: true },
      { args: [""], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Container With Most Water",
    statement: "Given n non-negative integers representing heights, find two lines that together with the x-axis forms a container that holds the most water. Return the maximum water volume.",
    difficulty: "medium",
    constraints: ["2 <= height.length <= 1000", "0 <= height[i] <= 10000"],
    functionSignature: { name: "maxWater", params: [{ name: "height", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,8,6,2,5,4,8,3,7]], output: 49 }],
    testCases: [
      { args: [[1,8,6,2,5,4,8,3,7]], expectedOutput: 49, isHidden: false },
      { args: [[1,1]], expectedOutput: 1, isHidden: false },
      { args: [[4,3,2,1,4]], expectedOutput: 16, isHidden: true },
      { args: [[1,2,1]], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Squares of Sorted Array",
    statement: "Given an integer array sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "sortedSquares", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[-4,-1,0,3,10]], output: [0,1,9,16,100] }],
    testCases: [
      { args: [[-4,-1,0,3,10]], expectedOutput: [0,1,9,16,100], isHidden: false },
      { args: [[-7,-3,2,3,11]], expectedOutput: [4,9,9,49,121], isHidden: false },
      { args: [[1,2,3]], expectedOutput: [1,4,9], isHidden: true },
      { args: [[-3,-2,-1]], expectedOutput: [1,4,9], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Find All Duplicates",
    statement: "Given an array of integers in range [1, n] where n is the array length, return all elements that appear twice.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "1 <= nums[i] <= nums.length"],
    functionSignature: { name: "findDuplicates", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[4,3,2,7,8,2,3,1]], output: [2,3] }],
    testCases: [
      { args: [[4,3,2,7,8,2,3,1]], expectedOutput: [2,3], isHidden: false },
      { args: [[1,1,2]], expectedOutput: [1], isHidden: false },
      { args: [[1]], expectedOutput: [], isHidden: true },
      { args: [[2,1,2,1]], expectedOutput: [1,2], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Sum Circular Subarray",
    statement: "Given a circular integer array, return the maximum possible sum of a non-empty subarray. The array is circular meaning the end wraps around to the start.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "-30000 <= nums[i] <= 30000"],
    functionSignature: { name: "maxCircularSubarraySum", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,-2,3,-2]], output: 3 }, { args: [[5,-3,5]], output: 10 }],
    testCases: [
      { args: [[1,-2,3,-2]], expectedOutput: 3, isHidden: false },
      { args: [[5,-3,5]], expectedOutput: 10, isHidden: false },
      { args: [[-3,-2,-3]], expectedOutput: -2, isHidden: true },
      { args: [[3,1,2]], expectedOutput: 6, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Spiral Matrix Values",
    statement: "Given m x n matrix dimensions and a flat array of values (filled row by row), return the values in spiral order.",
    difficulty: "medium",
    constraints: ["1 <= m, n <= 10", "m*n = nums.length"],
    functionSignature: { name: "spiralOrder", params: [{ name: "nums", type: "number[]" }, { name: "cols", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3,4,5,6,7,8,9], 3], output: [1,2,3,6,9,8,7,4,5], explanation: "3x3 matrix spiral" }],
    testCases: [
      { args: [[1,2,3,4,5,6,7,8,9], 3], expectedOutput: [1,2,3,6,9,8,7,4,5], isHidden: false },
      { args: [[1,2,3,4], 2], expectedOutput: [1,2,4,3], isHidden: false },
      { args: [[1,2,3,4,5,6], 3], expectedOutput: [1,2,3,6,5,4], isHidden: true },
      { args: [[1]], expectedOutput: [1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Jump Game",
    statement: "Given an array where each element is the maximum jump length from that position, return true if you can reach the last index starting from index 0.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "0 <= nums[i] <= 10000"],
    functionSignature: { name: "canJump", params: [{ name: "nums", type: "number[]" }], returnType: "boolean" },
    examples: [{ args: [[2,3,1,1,4]], output: true }, { args: [[3,2,1,0,4]], output: false }],
    testCases: [
      { args: [[2,3,1,1,4]], expectedOutput: true, isHidden: false },
      { args: [[3,2,1,0,4]], expectedOutput: false, isHidden: false },
      { args: [[0]], expectedOutput: true, isHidden: true },
      { args: [[2,0,0]], expectedOutput: true, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "String to Integer (atoi)",
    statement: "Implement a function that converts a string to a 32-bit signed integer. Skip leading whitespace, handle optional +/- sign, read digits, and clamp to [-2^31, 2^31-1].",
    difficulty: "medium",
    constraints: ["0 <= s.length <= 200"],
    functionSignature: { name: "myAtoi", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["42"], output: 42 }, { args: ["   -42"], output: -42 }],
    testCases: [
      { args: ["42"], expectedOutput: 42, isHidden: false },
      { args: ["   -42"], expectedOutput: -42, isHidden: false },
      { args: ["4193 with words"], expectedOutput: 4193, isHidden: true },
      { args: ["words and 987"], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Size Subarray Sum",
    statement: "Given a positive integer target and an array of positive integers, return the minimal length of a contiguous subarray whose sum is >= target. Return 0 if no such subarray exists.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "1 <= nums[i] <= 10000", "1 <= target <= 10^9"],
    functionSignature: { name: "minSubArrayLen", params: [{ name: "nums", type: "number[]" }, { name: "target", type: "number" }], returnType: "number" },
    examples: [{ args: [[2,3,1,2,4,3], 7], output: 2, explanation: "[4,3] has length 2" }],
    testCases: [
      { args: [[2,3,1,2,4,3], 7], expectedOutput: 2, isHidden: false },
      { args: [[1,4,4], 4], expectedOutput: 1, isHidden: false },
      { args: [[1,1,1,1,1,1,1,1], 11], expectedOutput: 0, isHidden: true },
      { args: [[1,2,3,4,5], 11], expectedOutput: 3, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Average Subarray",
    statement: "Given an integer array and integer k, return the maximum average of a subarray of length exactly k.",
    difficulty: "medium",
    constraints: ["1 <= k <= nums.length <= 10000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "findMaxAverage", params: [{ name: "nums", type: "number[]" }, { name: "k", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,12,-5,-6,50,3], 4], output: 12, explanation: "(12-5-6+50)/4 = 12.75, but max is 12 after floor... actually 12.75 rounded" }],
    testCases: [
      { args: [[1,12,-5,-6,50,3], 4], expectedOutput: 12, isHidden: false },
      { args: [[5], 1], expectedOutput: 5, isHidden: false },
      { args: [[0,4,0,3,2], 1], expectedOutput: 4, isHidden: true },
      { args: [[3,3,3,3], 2], expectedOutput: 3, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Next Greater Element",
    statement: "Given an array, return an array where each element is replaced by the next greater element to its right. If none exists, use -1.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "nextGreaterElement", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[4,5,2,10]], output: [5,10,10,-1] }],
    testCases: [
      { args: [[4,5,2,10]], expectedOutput: [5,10,10,-1], isHidden: false },
      { args: [[3,2,1]], expectedOutput: [-1,-1,-1], isHidden: false },
      { args: [[1,2,3]], expectedOutput: [2,3,-1], isHidden: true },
      { args: [[5]], expectedOutput: [-1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Decode Run-Length String",
    statement: "Given a run-length encoded string like '3a2b1c', decode it to 'aaabbc'. Each group is a digit followed by a character.",
    difficulty: "medium",
    constraints: ["1 <= s.length <= 100", "s consists of digit-letter pairs", "1 <= count <= 9"],
    functionSignature: { name: "decodeRLE", params: [{ name: "s", type: "string" }], returnType: "string" },
    examples: [{ args: ["3a2b1c"], output: "aaabbc" }],
    testCases: [
      { args: ["3a2b1c"], expectedOutput: "aaabbc", isHidden: false },
      { args: ["1a"], expectedOutput: "a", isHidden: false },
      { args: ["4z"], expectedOutput: "zzzz", isHidden: true },
      { args: ["2h3e1l"], expectedOutput: "hheeel", isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Find Pivot Index",
    statement: "Return the leftmost pivot index where the sum of all elements to the left equals the sum to the right. Return -1 if none exists.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 10000", "-1000 <= nums[i] <= 1000"],
    functionSignature: { name: "pivotIndex", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,7,3,6,5,6]], output: 3 }],
    testCases: [
      { args: [[1,7,3,6,5,6]], expectedOutput: 3, isHidden: false },
      { args: [[1,2,3]], expectedOutput: -1, isHidden: false },
      { args: [[2,1,-1]], expectedOutput: 0, isHidden: true },
      { args: [[-1,-1,-1,-1,-1,0]], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Number of Arrows to Burst Balloons",
    statement: "Balloons are represented as intervals [start, end]. An arrow shot at x bursts all balloons with start <= x <= end. Return minimum arrows needed to burst all balloons.",
    difficulty: "medium",
    constraints: ["1 <= points.length <= 1000", "Each point is [start, end] encoded as start*10000+end"],
    functionSignature: { name: "minArrows", params: [{ name: "starts", type: "number[]" }, { name: "ends", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[10,30,15,35],[19,25,20,39]], output: 2 }],
    testCases: [
      { args: [[10,30,15,35],[19,25,20,39]], expectedOutput: 2, isHidden: false },
      { args: [[1],[2]], expectedOutput: 1, isHidden: false },
      { args: [[1,2],[2,3]], expectedOutput: 1, isHidden: true },
      { args: [[1,4,5,6,7,8,9,10,11,12],[2,8,6,8,10,12,13,14,15,16]], expectedOutput: 4, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Unique Paths Count",
    statement: "A robot is on an m x n grid at the top-left corner. It can only move right or down. Return the number of unique paths to reach the bottom-right corner.",
    difficulty: "medium",
    constraints: ["1 <= m, n <= 20"],
    functionSignature: { name: "uniquePaths", params: [{ name: "m", type: "number" }, { name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [3,7], output: 28 }],
    testCases: [
      { args: [3,7], expectedOutput: 28, isHidden: false },
      { args: [3,2], expectedOutput: 3, isHidden: false },
      { args: [1,1], expectedOutput: 1, isHidden: true },
      { args: [4,4], expectedOutput: 20, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Absolute Difference",
    statement: "Given an array of distinct integers, return a list of pairs with the minimum absolute difference, sorted by the first element of each pair.",
    difficulty: "medium",
    constraints: ["2 <= arr.length <= 1000", "-10^6 <= arr[i] <= 10^6"],
    functionSignature: { name: "minimumAbsDifference", params: [{ name: "arr", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[4,2,1,3]], output: [1,2,2,3,3,4], explanation: "Pairs [1,2],[2,3],[3,4] flattened" }],
    testCases: [
      { args: [[4,2,1,3]], expectedOutput: [1,2,2,3,3,4], isHidden: false },
      { args: [[1,3,6,10,15]], expectedOutput: [1,3], isHidden: false },
      { args: [[3,8,-10,23,19,-4,-14,27]], expectedOutput: [-14,-10,19,23], isHidden: true },
      { args: [[1,2]], expectedOutput: [1,2], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Frequency Sort",
    statement: "Sort an array of integers by frequency (most frequent first). Ties are broken by value in descending order.",
    difficulty: "medium",
    constraints: ["1 <= nums.length <= 1000", "-100 <= nums[i] <= 100"],
    functionSignature: { name: "frequencySort", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,1,2,2,2,3]], output: [2,2,2,1,1,3] }],
    testCases: [
      { args: [[1,1,2,2,2,3]], expectedOutput: [2,2,2,1,1,3], isHidden: false },
      { args: [[2,3,1,3,2]], expectedOutput: [3,3,2,2,1], isHidden: false },
      { args: [[1]], expectedOutput: [1], isHidden: true },
      { args: [[-1,1,-6,4,5,-6,1,4,1]], expectedOutput: [1,1,1,4,4,-6,-6,5,-1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Platforms",
    statement: "Given arrival and departure times of trains, return the minimum number of platforms needed so no train waits.",
    difficulty: "medium",
    constraints: ["1 <= n <= 1000", "0 <= arr[i], dep[i] <= 2400", "arr[i] <= dep[i]"],
    functionSignature: { name: "minPlatforms", params: [{ name: "arr", type: "number[]" }, { name: "dep", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[900,940,950,1100,1500,1800],[910,1200,1120,1130,1900,2000]], output: 3 }],
    testCases: [
      { args: [[900,940,950,1100,1500,1800],[910,1200,1120,1130,1900,2000]], expectedOutput: 3, isHidden: false },
      { args: [[900,1100],[1000,1200]], expectedOutput: 2, isHidden: false },
      { args: [[100],[200]], expectedOutput: 1, isHidden: true },
      { args: [[200,210,300,320,350],[230,340,320,430,400]], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Group Anagrams Count",
    statement: "Given an array of strings, return the number of distinct anagram groups.",
    difficulty: "medium",
    constraints: ["1 <= strs.length <= 1000", "0 <= strs[i].length <= 100"],
    functionSignature: { name: "groupAnagramsCount", params: [{ name: "strs", type: "string[]" }], returnType: "number" },
    examples: [{ args: [["eat","tea","tan","ate","nat","bat"]], output: 3 }],
    testCases: [
      { args: [["eat","tea","tan","ate","nat","bat"]], expectedOutput: 3, isHidden: false },
      { args: [["a"]], expectedOutput: 1, isHidden: false },
      { args: [["abc","cba","bac","xyz"]], expectedOutput: 2, isHidden: true },
      { args: [["a","b","c"]], expectedOutput: 3, isHidden: true },
    ],
    sourceKind: "permissive",
  },

  // ═══════════════════════════════════════
  // HARD (30 problems)
  // ═══════════════════════════════════════

  {
    mode: "competitive", title: "Coin Change",
    statement: "Given coin denominations and a target amount, return the minimum number of coins to make the amount. Return -1 if impossible.",
    difficulty: "hard",
    constraints: ["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10000"],
    functionSignature: { name: "coinChange", params: [{ name: "coins", type: "number[]" }, { name: "amount", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,2,5], 11], output: 3, explanation: "5+5+1" }],
    testCases: [
      { args: [[1,2,5], 11], expectedOutput: 3, isHidden: false },
      { args: [[2], 3], expectedOutput: -1, isHidden: false },
      { args: [[1], 0], expectedOutput: 0, isHidden: true },
      { args: [[1,5,6,9], 11], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Longest Increasing Subsequence",
    statement: "Return the length of the longest strictly increasing subsequence in an array.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 2500", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "lengthOfLIS", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[10,9,2,5,3,7,101,18]], output: 4 }],
    testCases: [
      { args: [[10,9,2,5,3,7,101,18]], expectedOutput: 4, isHidden: false },
      { args: [[0,1,0,3,2,3]], expectedOutput: 4, isHidden: false },
      { args: [[7,7,7,7,7]], expectedOutput: 1, isHidden: true },
      { args: [[1,3,6,7,9,4,10,5,6]], expectedOutput: 6, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Product Subarray",
    statement: "Find the contiguous subarray with the largest product and return that product.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 20000", "-10 <= nums[i] <= 10"],
    functionSignature: { name: "maxProduct", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[2,3,-2,4]], output: 6 }],
    testCases: [
      { args: [[2,3,-2,4]], expectedOutput: 6, isHidden: false },
      { args: [[-2,0,-1]], expectedOutput: 0, isHidden: false },
      { args: [[-2,3,-4]], expectedOutput: 24, isHidden: true },
      { args: [[1,-2,-3,4]], expectedOutput: 24, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Word Break",
    statement: "Given a string s and a dictionary of words, return true if s can be segmented into space-separated dictionary words.",
    difficulty: "hard",
    constraints: ["1 <= s.length <= 300", "1 <= wordDict.length <= 1000"],
    functionSignature: { name: "wordBreak", params: [{ name: "s", type: "string" }, { name: "wordDict", type: "string[]" }], returnType: "boolean" },
    examples: [{ args: ["leetcode", ["leet","code"]], output: true }],
    testCases: [
      { args: ["leetcode", ["leet","code"]], expectedOutput: true, isHidden: false },
      { args: ["applepenapple", ["apple","pen"]], expectedOutput: true, isHidden: false },
      { args: ["catsandog", ["cats","dog","sand","and","cat"]], expectedOutput: false, isHidden: true },
      { args: ["ab", ["a","b"]], expectedOutput: true, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Trapping Rain Water",
    statement: "Given n non-negative integers representing an elevation map where each bar has width 1, compute how much water it can trap after raining.",
    difficulty: "hard",
    constraints: ["1 <= height.length <= 2*10^4", "0 <= height[i] <= 10^5"],
    functionSignature: { name: "trap", params: [{ name: "height", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[0,1,0,2,1,0,1,3,2,1,2,1]], output: 6 }],
    testCases: [
      { args: [[0,1,0,2,1,0,1,3,2,1,2,1]], expectedOutput: 6, isHidden: false },
      { args: [[4,2,0,3,2,5]], expectedOutput: 9, isHidden: false },
      { args: [[1,0,1]], expectedOutput: 1, isHidden: true },
      { args: [[3,0,2,0,4]], expectedOutput: 7, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Path Sum",
    statement: "Given an m x n grid of non-negative integers (as a flat array, row-major), find the path from top-left to bottom-right that minimizes the sum. You can only move right or down.",
    difficulty: "hard",
    constraints: ["1 <= m, n <= 20", "0 <= grid[i][j] <= 100"],
    functionSignature: { name: "minPathSum", params: [{ name: "grid", type: "number[]" }, { name: "cols", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,3,1,1,5,1,4,2,1], 3], output: 7, explanation: "1→3→1→1→1=7" }],
    testCases: [
      { args: [[1,3,1,1,5,1,4,2,1], 3], expectedOutput: 7, isHidden: false },
      { args: [[1,2,3,4,5,6], 3], expectedOutput: 12, isHidden: false },
      { args: [[1], 1], expectedOutput: 1, isHidden: true },
      { args: [[1,2,5,3], 2], expectedOutput: 6, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Decode Ways",
    statement: "A message is encoded as digits where 1→A, 2→B, ..., 26→Z. Given a digit string, return the number of ways to decode it.",
    difficulty: "hard",
    constraints: ["1 <= s.length <= 100", "s contains only digits", "s may contain leading zeros"],
    functionSignature: { name: "numDecodings", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["12"], output: 2, explanation: "'AB' or 'L'" }],
    testCases: [
      { args: ["12"], expectedOutput: 2, isHidden: false },
      { args: ["226"], expectedOutput: 3, isHidden: false },
      { args: ["0"], expectedOutput: 0, isHidden: true },
      { args: ["11106"], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Largest Rectangle in Histogram",
    statement: "Given an array of integers representing the heights of bars in a histogram, return the area of the largest rectangle.",
    difficulty: "hard",
    constraints: ["1 <= heights.length <= 10000", "0 <= heights[i] <= 10000"],
    functionSignature: { name: "largestRectangleArea", params: [{ name: "heights", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[2,1,5,6,2,3]], output: 10 }],
    testCases: [
      { args: [[2,1,5,6,2,3]], expectedOutput: 10, isHidden: false },
      { args: [[2,4]], expectedOutput: 4, isHidden: false },
      { args: [[1,1]], expectedOutput: 2, isHidden: true },
      { args: [[6,2,5,4,5,1,6]], expectedOutput: 12, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Window Substring Length",
    statement: "Given strings s and t, return the length of the minimum window in s that contains all characters of t. Return 0 if no such window.",
    difficulty: "hard",
    constraints: ["1 <= s.length, t.length <= 1000", "s and t consist of uppercase and lowercase English letters"],
    functionSignature: { name: "minWindowLength", params: [{ name: "s", type: "string" }, { name: "t", type: "string" }], returnType: "number" },
    examples: [{ args: ["ADOBECODEBANC", "ABC"], output: 4, explanation: "'BANC' is the minimum window" }],
    testCases: [
      { args: ["ADOBECODEBANC", "ABC"], expectedOutput: 4, isHidden: false },
      { args: ["a", "a"], expectedOutput: 1, isHidden: false },
      { args: ["a", "aa"], expectedOutput: 0, isHidden: true },
      { args: ["cabwefgewcwaefgcf", "cae"], expectedOutput: 4, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Edit Distance",
    statement: "Given two strings, return the minimum number of single-character edits (insert, delete, replace) required to transform word1 into word2.",
    difficulty: "hard",
    constraints: ["0 <= word1.length, word2.length <= 500"],
    functionSignature: { name: "editDistance", params: [{ name: "word1", type: "string" }, { name: "word2", type: "string" }], returnType: "number" },
    examples: [{ args: ["horse", "ros"], output: 3 }],
    testCases: [
      { args: ["horse", "ros"], expectedOutput: 3, isHidden: false },
      { args: ["intention", "execution"], expectedOutput: 5, isHidden: false },
      { args: ["", ""], expectedOutput: 0, isHidden: true },
      { args: ["abc", "abc"], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Burst Balloons",
    statement: "You have n balloons with numbers. If you burst balloon i, you earn nums[left]*nums[i]*nums[right] coins. Return maximum coins from bursting all balloons. Boundaries are treated as 1.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 15", "0 <= nums[i] <= 100"],
    functionSignature: { name: "maxCoins", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[3,1,5,8]], output: 167 }],
    testCases: [
      { args: [[3,1,5,8]], expectedOutput: 167, isHidden: false },
      { args: [[1,5]], expectedOutput: 10, isHidden: false },
      { args: [[1]], expectedOutput: 1, isHidden: true },
      { args: [[1,2,3]], expectedOutput: 12, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "K Closest Points to Origin",
    statement: "Given an array of points as [x1,y1,x2,y2,...] and integer k, return the k closest points to the origin (0,0). Return their coordinates flattened, sorted by distance then x then y.",
    difficulty: "hard",
    constraints: ["1 <= k <= points.length/2 <= 500", "-10000 <= points[i] <= 10000"],
    functionSignature: { name: "kClosest", params: [{ name: "points", type: "number[]" }, { name: "k", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[1,3,-2,2], 1], output: [-2,2], explanation: "sqrt(8) < sqrt(10)" }],
    testCases: [
      { args: [[1,3,-2,2], 1], expectedOutput: [-2,2], isHidden: false },
      { args: [[3,3,5,-1,-2,4], 2], expectedOutput: [-2,4,3,3], isHidden: false },
      { args: [[0,1,1,0], 2], expectedOutput: [0,1,1,0], isHidden: true },
      { args: [[1,1], 1], expectedOutput: [1,1], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Median of Two Sorted Arrays",
    statement: "Given two sorted arrays, find the median of the combined array. If even length, return the lower middle element.",
    difficulty: "hard",
    constraints: ["0 <= nums1.length, nums2.length <= 1000", "Combined length >= 1"],
    functionSignature: { name: "findMedian", params: [{ name: "nums1", type: "number[]" }, { name: "nums2", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,3],[2]], output: 2, explanation: "Combined sorted: [1,2,3], median is 2" }],
    testCases: [
      { args: [[1,3],[2]], expectedOutput: 2, isHidden: false },
      { args: [[1,2],[3,4]], expectedOutput: 2, isHidden: false },
      { args: [[0,0],[0,0]], expectedOutput: 0, isHidden: true },
      { args: [[],[1]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Partition Equal Subset Sum",
    statement: "Given an array of positive integers, determine if it can be partitioned into two subsets with equal sum.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 200", "1 <= nums[i] <= 100"],
    functionSignature: { name: "canPartition", params: [{ name: "nums", type: "number[]" }], returnType: "boolean" },
    examples: [{ args: [[1,5,11,5]], output: true, explanation: "[1,5,5] and [11]" }],
    testCases: [
      { args: [[1,5,11,5]], expectedOutput: true, isHidden: false },
      { args: [[1,2,3,5]], expectedOutput: false, isHidden: false },
      { args: [[1,1]], expectedOutput: true, isHidden: true },
      { args: [[3,3,3,4,5]], expectedOutput: true, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Largest Divisible Subset",
    statement: "Given a set of distinct positive integers, return the largest subset where every pair (a,b) satisfies a % b == 0 or b % a == 0. Return the sorted subset.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 1000", "1 <= nums[i] <= 2*10^9", "All elements are distinct"],
    functionSignature: { name: "largestDivisibleSubset", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[1,2,3]], output: [1,2], explanation: "[1,2] or [1,3] are both valid" }],
    testCases: [
      { args: [[1,2,4,8]], expectedOutput: [1,2,4,8], isHidden: false },
      { args: [[1,2,3]], expectedOutput: [1,2], isHidden: false },
      { args: [[1]], expectedOutput: [1], isHidden: true },
      { args: [[3,4,16,8]], expectedOutput: [4,8,16], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Palindrome Partitioning Min Cuts",
    statement: "Given a string, return the minimum number of cuts needed to partition it so every substring is a palindrome.",
    difficulty: "hard",
    constraints: ["1 <= s.length <= 2000", "s consists of lowercase letters only"],
    functionSignature: { name: "minCut", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["aab"], output: 1, explanation: "'aa' | 'b'" }],
    testCases: [
      { args: ["aab"], expectedOutput: 1, isHidden: false },
      { args: ["a"], expectedOutput: 0, isHidden: false },
      { args: ["ab"], expectedOutput: 1, isHidden: true },
      { args: ["aba"], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Number of Islands",
    statement: "Given a flat array representing an m x n grid of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and formed by connecting adjacent land cells horizontally or vertically.",
    difficulty: "hard",
    constraints: ["1 <= m, n <= 30", "grid values are '0' or '1'"],
    functionSignature: { name: "numIslands", params: [{ name: "grid", type: "string[]" }, { name: "cols", type: "number" }], returnType: "number" },
    examples: [{ args: [["1","1","1","1","0","1","1","0","1","0","1","0","0","0","0","0","0","1","1","1"],4], output: 3 }],
    testCases: [
      { args: [["1","1","1","1","0","1","1","0","1","0","1","0","0","0","0","0","0","1","1","1"], 4], expectedOutput: 3, isHidden: false },
      { args: [["1","1","0","0","0","1","1","0","0","0","0","0","1","0","0","0","0","0","1","1"],4], expectedOutput: 3, isHidden: false },
      { args: [["1"],1], expectedOutput: 1, isHidden: true },
      { args: [["0"],1], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Knapsack 0/1",
    statement: "Given item weights and values, and a capacity W, return the maximum value achievable without exceeding capacity. Each item can be used at most once.",
    difficulty: "hard",
    constraints: ["1 <= n <= 100", "0 <= weights[i], values[i] <= 1000", "0 <= W <= 1000"],
    functionSignature: { name: "knapsack", params: [{ name: "weights", type: "number[]" }, { name: "values", type: "number[]" }, { name: "W", type: "number" }], returnType: "number" },
    examples: [{ args: [[1,3,4,5],[1,4,5,7], 7], output: 9 }],
    testCases: [
      { args: [[1,3,4,5],[1,4,5,7], 7], expectedOutput: 9, isHidden: false },
      { args: [[2,3,4],[3,4,5], 5], expectedOutput: 7, isHidden: false },
      { args: [[1],[10], 0], expectedOutput: 0, isHidden: true },
      { args: [[1,2,3],[6,10,12], 5], expectedOutput: 22, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Longest Palindromic Substring Length",
    statement: "Given a string s, return the length of its longest palindromic substring.",
    difficulty: "hard",
    constraints: ["1 <= s.length <= 1000", "s consists of digits and letters"],
    functionSignature: { name: "longestPalindromeLength", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["babad"], output: 3, explanation: "'bab' or 'aba'" }],
    testCases: [
      { args: ["babad"], expectedOutput: 3, isHidden: false },
      { args: ["cbbd"], expectedOutput: 2, isHidden: false },
      { args: ["a"], expectedOutput: 1, isHidden: true },
      { args: ["racecar"], expectedOutput: 7, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Regular Expression Matching",
    statement: "Implement regex matching with '.' (matches any single character) and '*' (matches zero or more of the preceding element). Return true if the pattern matches the entire string.",
    difficulty: "hard",
    constraints: ["1 <= s.length <= 20", "1 <= p.length <= 30", "s contains only lowercase letters", "p contains lowercase letters, '.', and '*'"],
    functionSignature: { name: "isMatch", params: [{ name: "s", type: "string" }, { name: "p", type: "string" }], returnType: "boolean" },
    examples: [{ args: ["aa", "a*"], output: true }, { args: ["ab", ".*"], output: true }],
    testCases: [
      { args: ["aa", "a*"], expectedOutput: true, isHidden: false },
      { args: ["ab", ".*"], expectedOutput: true, isHidden: false },
      { args: ["aab", "c*a*b"], expectedOutput: true, isHidden: true },
      { args: ["mississippi", "mis*is*p*."], expectedOutput: false, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Number of Longest Increasing Subsequences",
    statement: "Given an integer array, return the number of longest strictly increasing subsequences.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 2000", "-10^6 <= nums[i] <= 10^6"],
    functionSignature: { name: "findNumberOfLIS", params: [{ name: "nums", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,3,5,4,7]], output: 2, explanation: "[1,3,5,7] and [1,3,4,7]" }],
    testCases: [
      { args: [[1,3,5,4,7]], expectedOutput: 2, isHidden: false },
      { args: [[2,2,2,2,2]], expectedOutput: 5, isHidden: false },
      { args: [[1,2,4,3,5,4,7,2]], expectedOutput: 3, isHidden: true },
      { args: [[1]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Number of Refueling Stops",
    statement: "A car starts at 0 with some initial fuel. Stations are at positions with available fuel. Return minimum stops to reach target, or -1 if impossible.",
    difficulty: "hard",
    constraints: ["1 <= target <= 10^9", "0 <= startFuel <= target", "0 <= stations.length <= 500"],
    functionSignature: { name: "minRefuelStops", params: [{ name: "target", type: "number" }, { name: "startFuel", type: "number" }, { name: "positions", type: "number[]" }, { name: "fuels", type: "number[]" }], returnType: "number" },
    examples: [{ args: [1, 1, [], []], output: 0 }],
    testCases: [
      { args: [1, 1, [], []], expectedOutput: 0, isHidden: false },
      { args: [100, 1, [10,20,30,40,50,60,70,80,90], [10,10,10,10,10,10,10,10,10]], expectedOutput: -1, isHidden: false },
      { args: [100, 10, [10,60,90], [60,30,30]], expectedOutput: 2, isHidden: true },
      { args: [100, 100, [], []], expectedOutput: 0, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Maximum Profit with Cooldown",
    statement: "Given stock prices, find the maximum profit. You may buy and sell on any day but must wait one day cooldown after each sell before buying again.",
    difficulty: "hard",
    constraints: ["1 <= prices.length <= 5000", "0 <= prices[i] <= 1000"],
    functionSignature: { name: "maxProfitCooldown", params: [{ name: "prices", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,2,3,0,2]], output: 3, explanation: "Buy@1 Sell@3 cooldown Buy@0 Sell@2 = 3" }],
    testCases: [
      { args: [[1,2,3,0,2]], expectedOutput: 3, isHidden: false },
      { args: [[1]], expectedOutput: 0, isHidden: false },
      { args: [[2,1,4]], expectedOutput: 3, isHidden: true },
      { args: [[6,1,3,2,4,7]], expectedOutput: 6, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Max Points on a Line",
    statement: "Given n points on a 2D plane as a flat array [x1,y1,x2,y2,...], return the maximum number of points that lie on the same straight line.",
    difficulty: "hard",
    constraints: ["2 <= n <= 300", "-10^4 <= points[i] <= 10^4"],
    functionSignature: { name: "maxPoints", params: [{ name: "points", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[1,1,2,2,3,3]], output: 3 }],
    testCases: [
      { args: [[1,1,2,2,3,3]], expectedOutput: 3, isHidden: false },
      { args: [[1,1,3,2,5,3,4,1,2,3,1,4]], expectedOutput: 4, isHidden: false },
      { args: [[0,0,1,1]], expectedOutput: 2, isHidden: true },
      { args: [[0,0,0,1,1,1]], expectedOutput: 3, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Minimum Cost to Hire K Workers",
    statement: "Workers have quality and minimum wage. You must hire k workers such that each worker is paid at least their wage, and ratios are the same. Return minimum cost to hire exactly k workers.",
    difficulty: "hard",
    constraints: ["1 <= k <= workers.length <= 100", "1 <= quality[i], wage[i] <= 10^4"],
    functionSignature: { name: "mincostToHireWorkers", params: [{ name: "quality", type: "number[]" }, { name: "wage", type: "number[]" }, { name: "k", type: "number" }], returnType: "number" },
    examples: [{ args: [[10,20,5],[70,50,30], 2], output: 105 }],
    testCases: [
      { args: [[10,20,5],[70,50,30], 2], expectedOutput: 105, isHidden: false },
      { args: [[3,1,10,10,1],[4,8,2,2,7], 3], expectedOutput: 30, isHidden: false },
      { args: [[1],[1], 1], expectedOutput: 1, isHidden: true },
      { args: [[1,2,3],[1,2,3], 2], expectedOutput: 3, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Sliding Window Maximum",
    statement: "Given an array and a window size k, return an array of the maximums of each window as it slides from left to right.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 10000", "-10000 <= nums[i] <= 10000", "1 <= k <= nums.length"],
    functionSignature: { name: "slidingWindowMax", params: [{ name: "nums", type: "number[]" }, { name: "k", type: "number" }], returnType: "number[]" },
    examples: [{ args: [[1,3,-1,-3,5,3,6,7], 3], output: [3,3,5,5,6,7] }],
    testCases: [
      { args: [[1,3,-1,-3,5,3,6,7], 3], expectedOutput: [3,3,5,5,6,7], isHidden: false },
      { args: [[1], 1], expectedOutput: [1], isHidden: false },
      { args: [[9,8,7,6,5], 2], expectedOutput: [9,8,7,6], isHidden: true },
      { args: [[1,2,3,4,5], 3], expectedOutput: [3,4,5], isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Cherry Pickup",
    statement: "Walk from (0,0) to (n-1,n-1) and back on an n x n grid picking up cherries (1=cherry,0=empty,-1=thorn). Return max cherries. Grid given as flat array row-major.",
    difficulty: "hard",
    constraints: ["1 <= n <= 10", "grid[i] is -1, 0, or 1"],
    functionSignature: { name: "cherryPickup", params: [{ name: "grid", type: "number[]" }, { name: "n", type: "number" }], returnType: "number" },
    examples: [{ args: [[0,1,-1,1,0,-1,1,1,1], 3], output: 5 }],
    testCases: [
      { args: [[0,1,-1,1,0,-1,1,1,1], 3], expectedOutput: 5, isHidden: false },
      { args: [[1,1,-1,1,-1,1,-1,1,1], 3], expectedOutput: 0, isHidden: false },
      { args: [[1], 1], expectedOutput: 1, isHidden: true },
      { args: [[1,1,1,1], 2], expectedOutput: 4, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Longest Valid Parentheses",
    statement: "Given a string of '(' and ')', return the length of the longest valid parentheses substring.",
    difficulty: "hard",
    constraints: ["0 <= s.length <= 3*10^4", "s consists of '(' and ')' only"],
    functionSignature: { name: "longestValidParentheses", params: [{ name: "s", type: "string" }], returnType: "number" },
    examples: [{ args: ["(()"], output: 2 }, { args: [")()())"], output: 4 }],
    testCases: [
      { args: ["(()"], expectedOutput: 2, isHidden: false },
      { args: [")()())"], expectedOutput: 4, isHidden: false },
      { args: [""], expectedOutput: 0, isHidden: true },
      { args: ["()(()"], expectedOutput: 2, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Best Time to Buy and Sell Stock III",
    statement: "Given stock prices, find the maximum profit from at most two non-overlapping buy-sell transactions.",
    difficulty: "hard",
    constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^5"],
    functionSignature: { name: "maxProfitTwoTx", params: [{ name: "prices", type: "number[]" }], returnType: "number" },
    examples: [{ args: [[3,3,5,0,0,3,1,4]], output: 6, explanation: "Buy@0 Sell@3 then Buy@1 Sell@4" }],
    testCases: [
      { args: [[3,3,5,0,0,3,1,4]], expectedOutput: 6, isHidden: false },
      { args: [[1,2,3,4,5]], expectedOutput: 4, isHidden: false },
      { args: [[7,6,4,3,1]], expectedOutput: 0, isHidden: true },
      { args: [[1,2]], expectedOutput: 1, isHidden: true },
    ],
    sourceKind: "permissive",
  },
  {
    mode: "competitive", title: "Count of Smaller Numbers After Self",
    statement: "Given an array, return an array where each element is the count of numbers to its right that are smaller than it.",
    difficulty: "hard",
    constraints: ["1 <= nums.length <= 1000", "-10000 <= nums[i] <= 10000"],
    functionSignature: { name: "countSmaller", params: [{ name: "nums", type: "number[]" }], returnType: "number[]" },
    examples: [{ args: [[5,2,6,1]], output: [2,1,1,0] }],
    testCases: [
      { args: [[5,2,6,1]], expectedOutput: [2,1,1,0], isHidden: false },
      { args: [[-1]], expectedOutput: [0], isHidden: false },
      { args: [[-1,-1]], expectedOutput: [0,0], isHidden: true },
      { args: [[1,2,3]], expectedOutput: [0,0,0], isHidden: true },
    ],
    sourceKind: "permissive",
  },
];